export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART'
export const ADD_ITEM_TO_INVENTORY = 'ADD_ITEM_TO_INVENTORY'
export const CONFIRM_PURCHASE = 'CONFIRM_PURCHASE'
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART'
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'
export const REMOVE_ITEM_FROM_INVENTORY = 'REMOVE_ITEM_FROM_INVENTORY'

